import type { InputFrame } from '../core/state';
export interface InputController { frame(): InputFrame; destroy(): void; reset(): void; }

export function createInputController(root: HTMLElement): InputController {
  const held = new Set<string>(); const pointers = new Map<number, string>(); let rotate: -1 | 0 | 1 = 0; let abilityPressed = false;
  const keydown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target?.closest('input, textarea, select, [contenteditable="true"]')) return; if (['ArrowLeft', 'ArrowRight', 'ArrowUp', ' ', 'a', 'A', 'd', 'D', 'w', 'W'].includes(event.key)) event.preventDefault(); held.add(event.key); if (event.key === 'q' || event.key === 'Q') abilityPressed = true; };
  const keyup = (event: KeyboardEvent) => held.delete(event.key);
  const pointer = (event: PointerEvent) => { const target = (event.target as HTMLElement).closest<HTMLElement>('[data-next-input]'); if (!target) return; const action = target.dataset.nextInput || ''; target.setPointerCapture?.(event.pointerId); pointers.set(event.pointerId, action); held.add(action); };
  const pointerup = (event: PointerEvent) => { const action = pointers.get(event.pointerId); if (!action) return; pointers.delete(event.pointerId); if (![...pointers.values()].includes(action)) held.delete(action); };
  window.addEventListener('keydown', keydown); window.addEventListener('keyup', keyup); root.addEventListener('pointerdown', pointer); root.addEventListener('pointerup', pointerup); root.addEventListener('pointercancel', pointerup);
  return { frame() { const leftHeld = held.has('ArrowLeft') || held.has('left') || held.has('a') || held.has('A'); const rightHeld = held.has('ArrowRight') || held.has('right') || held.has('d') || held.has('D'); rotate = rightHeld && !leftHeld ? 1 : leftHeld && !rightHeld ? -1 : 0; const frame = { rotate, leftHeld, rightHeld, thrust: held.has(' ') || held.has('ArrowUp') || held.has('w') || held.has('W') || held.has('thrust'), abilityPressed, bothTurnHeld: leftHeld && rightHeld, kickLeftPressed: false, kickRightPressed: false }; abilityPressed = false; return frame; }, reset() { held.clear(); pointers.clear(); abilityPressed = false; }, destroy() { window.removeEventListener('keydown', keydown); window.removeEventListener('keyup', keyup); root.removeEventListener('pointerdown', pointer); root.removeEventListener('pointerup', pointerup); root.removeEventListener('pointercancel', pointerup); } };
}
