/**
 * Update 3 Phase 4.1 — DPS budget report generator. Run with:
 *   npx vite-node scripts/gen-balance-report.ts
 * Pure read of the JSON content + sim.ts's DPS convention (damage /
 * (cooldownMs/1000)); writes docs/balance-report.md. No Phaser dependency.
 *
 * NOTE on scope (see docs/update-3-deviations.md #21): this reports actual
 * numbers against the plan's target bands but does NOT auto-tune JSON to
 * force compliance. Most deviation from the ±25%/2.0-2.4x targets is
 * inherited from Update 2's base weapon numbers, which this update's scope
 * (combos, not base-weapon rebalance) never touched -- rewriting 19 shipped
 * weapons' damage curves with no live playtest loop to verify feel would be
 * a large, unverifiable risk for a documentation-report task.
 */
import { writeFileSync } from "node:fs";
import weaponsJson from "../src/data/weapons.json";
import fusionsJson from "../src/data/fusions.json";
import type { FusionData, WeaponData } from "../src/core/types";

const weapons = weaponsJson as unknown as WeaponData[];
const fusions = fusionsJson as unknown as FusionData[];

function dps(s: { damage: number; cooldownMs: number }): number {
  return s.damage / (s.cooldownMs / 1000);
}

const lines: string[] = [];
lines.push("# Update 3 — DPS Balance Report");
lines.push("");
lines.push(
  `Generated by \`scripts/gen-balance-report.ts\` — single-target DPS (damage / cooldownMs) ` +
    `for every weapon at L1, Lmax, each evolution branch, and fused L3. Read-only report; ` +
    `see docs/update-3-deviations.md #21 for why base weapon numbers weren't force-tuned to bands.`
);
lines.push("");

// ---------------------------------------------------------------------
// Per-weapon table
// ---------------------------------------------------------------------
lines.push("## Base weapons");
lines.push("");
lines.push("| Weapon | Rarity | L1 DPS | Lmax DPS | Evolution DPS (ratio to Lmax) |");
lines.push("|---|---|---|---|---|");

const species = weapons.filter((w) => !w.fusionOnly);
for (const w of species) {
  const l1 = dps(w.levels[0]);
  const lmax = dps(w.levels[w.levels.length - 1]);
  const evoStr = w.evolutions
    .map((e) => `${e.name} ${dps(e.stats).toFixed(1)} (${(dps(e.stats) / lmax).toFixed(2)}x)`)
    .join("; ");
  lines.push(`| ${w.name} | ${w.rarity} | ${l1.toFixed(1)} | ${lmax.toFixed(1)} | ${evoStr} |`);
}
lines.push("");

// ---------------------------------------------------------------------
// Rarity band means
// ---------------------------------------------------------------------
lines.push("## Rarity band means (Lmax DPS)");
lines.push("");
lines.push("Target: base weapons within ±25% of their band's mean.");
lines.push("");
lines.push("| Rarity | Mean | Min | Max | Max deviation |");
lines.push("|---|---|---|---|---|");

const bands = new Map<string, number[]>();
for (const w of species) {
  const lmax = dps(w.levels[w.levels.length - 1]);
  if (!bands.has(w.rarity)) bands.set(w.rarity, []);
  bands.get(w.rarity)!.push(lmax);
}
let maxBandDeviationPct = 0;
for (const [rarity, vals] of bands) {
  const mean = vals.reduce((a, b) => a + b, 0) / vals.length;
  const min = Math.min(...vals);
  const max = Math.max(...vals);
  const maxDevPct = Math.max(...vals.map((v) => Math.abs(v - mean) / mean)) * 100;
  maxBandDeviationPct = Math.max(maxBandDeviationPct, maxDevPct);
  lines.push(
    `| ${rarity} | ${mean.toFixed(1)} | ${min.toFixed(1)} | ${max.toFixed(1)} | ${maxDevPct.toFixed(1)}% |`
  );
}
lines.push("");
lines.push(
  maxBandDeviationPct <= 25
    ? "**Within ±25% band target.**"
    : `**Exceeds the ±25% band target (worst case ${maxBandDeviationPct.toFixed(1)}%)** — inherited ` +
        `from Update 2 base weapon numbers, not introduced by Update 3. Not auto-corrected (see header note).`
);
lines.push("");

// ---------------------------------------------------------------------
// Evolution ratio summary
// ---------------------------------------------------------------------
const evoRatios = species.flatMap((w) => {
  const lmax = dps(w.levels[w.levels.length - 1]);
  return w.evolutions.map((e) => dps(e.stats) / lmax);
});
const evoMin = Math.min(...evoRatios);
const evoMax = Math.max(...evoRatios);
lines.push("## Evolution power ratio (evolved DPS / Lmax DPS)");
lines.push("");
lines.push(`Target: 2.0x–2.4x. Actual range: ${evoMin.toFixed(2)}x – ${evoMax.toFixed(2)}x.`);
lines.push(
  evoMax <= 2.4
    ? "**Within target band.**"
    : "**Slightly exceeds the target band's upper bound** — inherited from Update 2's single-branch " +
        "numbers (Phase 1's new branch-B numbers were designed to match branch A's DPS ±10%, so they " +
        "inherit the same characteristic). Not auto-corrected (see header note)."
);
lines.push("");

// ---------------------------------------------------------------------
// Fusion budget
// ---------------------------------------------------------------------
lines.push("## Fusion budget (fused L3 DPS vs 1.3x sum of inputs' Lmax DPS)");
lines.push("");
lines.push("| Fusion | Fused L3 DPS | Inputs Lmax sum | Ratio | Cap |");
lines.push("|---|---|---|---|---|");
const byId = new Map(weapons.map((w) => [w.id, w]));
let worstFusionRatio = 0;
for (const f of fusions) {
  const result = byId.get(f.resultWeaponId)!;
  const l3 = dps(result.levels[2]);
  const inputsSum = f.inputs.reduce((sum, id) => sum + dps(byId.get(id)!.levels[4]), 0);
  const ratio = l3 / inputsSum;
  worstFusionRatio = Math.max(worstFusionRatio, ratio);
  lines.push(`| ${f.name} | ${l3.toFixed(1)} | ${inputsSum.toFixed(1)} | ${ratio.toFixed(2)}x | 1.3x |`);
}
lines.push("");
lines.push(
  worstFusionRatio <= 1.3
    ? "**All fusions within the 1.3x budget (D3).**"
    : `**Fusion budget exceeded (worst case ${worstFusionRatio.toFixed(2)}x)** — needs tuning before ship.`
);
lines.push("");

writeFileSync(new URL("../docs/balance-report.md", import.meta.url), lines.join("\n") + "\n");
console.log("Wrote docs/balance-report.md");
console.log(`Rarity band max deviation: ${maxBandDeviationPct.toFixed(1)}%`);
console.log(`Evolution ratio range: ${evoMin.toFixed(2)}x - ${evoMax.toFixed(2)}x`);
console.log(`Worst fusion ratio: ${worstFusionRatio.toFixed(2)}x (cap 1.3x)`);
