import type { GameState } from '../core/state';
import { upgradeById } from '../content/upgrades';

export function titleScreen(state: GameState, hasCheckpoint: boolean): string { return `<section class="next-screen next-title"><p class="next-kicker">TOMFOOLERY / FLIGHT DECK 01</p><h1>Moon Lander</h1><p class="next-lede">A tiny expedition ship. A very large moon. Keep the copper legs between you and the dust.</p><div class="next-readout"><span>RULESET</span><b>LANDER 1.0</b><span>FLIGHT MODE</span><b>${state.run.difficulty.toUpperCase()}</b><span>RUN</span><b>${state.run.seed.toString(16).toUpperCase()}</b></div><div class="next-actions"><button data-next-action="start" class="next-primary">${hasCheckpoint ? 'Continue descent' : 'Start descent'}</button>${hasCheckpoint ? '<button data-next-action="new" class="next-secondary">New expedition <span>discard checkpoint</span></button>' : ''}<button data-next-action="training" class="next-secondary">Flight school <span>development route</span></button><button data-next-action="hangar" class="next-secondary">Open hangar <span>${state.run.stardust} ✦ stardust</span></button></div><p class="next-controls">Rotate <kbd>←</kbd><kbd>→</kbd> · Thrust <kbd>Space</kbd> · Pause <kbd>Esc</kbd></p></section>`; }
export function trainingScreen(): string { return `<section class="next-screen next-lesson"><p class="next-kicker">FLIGHT SCHOOL / 01—03</p><h2>Three things keep a pilot alive.</h2><ol><li><b>Thrust</b> to slow your fall. The plume points away from your acceleration.</li><li><b>Rotate</b> early. A level ship gives the landing legs room to work.</li><li><b>Touch down</b> over the copper-lit pad with low drift and low descent speed.</li></ol><div class="next-actions"><button data-next-action="start" class="next-primary">Try it now</button><button data-next-action="back" class="next-secondary">Back to title</button></div></section>`; }
export function hangarScreen(state: GameState): string { return `<section class="next-screen"><p class="next-kicker">HANGAR / PERSONAL KIT</p><h2>Make the little ship yours.</h2><p>${state.run.stardust} ✦ stardust available. The full paint, trail, and sky catalog stays local to this flight deck.</p><div class="next-readout"><span>PAINTS</span><b>6 available</b><span>TRAILS</span><b>6 available</b><span>SKIES</span><b>4 available</b></div><div class="next-actions"><button data-next-action="back" class="next-primary">Return to title</button></div></section>`; }
export function pauseScreen(): string { return `<section class="next-screen next-pause"><p class="next-kicker">FLIGHT HOLD</p><h2>Paused</h2><p>The ship and its instruments are holding position.</p><div class="next-actions"><button data-next-action="resume" class="next-primary">Resume flight</button><button data-next-action="settings" class="next-secondary">Settings</button><button data-next-action="quit" class="next-secondary">Return to title</button></div></section>`; }
export function crashScreen(state: GameState): string { return `<section class="next-screen next-result"><p class="next-kicker">SIGNAL LOST / DESCENT ${state.run.level}</p><h2>Dust happens.</h2><p class="next-diagnosis">${state.world.message}</p><div class="next-readout"><span>SCORE</span><b>${state.run.score}</b><span>LANDINGS</span><b>${state.run.stats.landings}</b><span>STARDUST</span><b>${state.run.stardust} ✦</b></div><div class="next-actions"><button data-next-action="retry" class="next-primary">Retry descent</button><button data-next-action="back" class="next-secondary">Flight deck</button></div></section>`; }
export function upgradeScreen(state: GameState): string { return `<section class="next-screen next-upgrades"><p class="next-kicker">TOUCHDOWN / LOADOUT WINDOW</p><h2>Choose what gets stranger.</h2><p>Untimed offer · skip with <button data-next-action="skip" class="next-inline">+15 ✦ stardust</button></p><div class="next-cards">${state.offer.map((id) => { const upgrade = upgradeById(id); return `<button class="next-card" data-next-upgrade="${id}"><span class="next-rarity">${upgrade.rarity}</span><strong>${upgrade.icon} ${upgrade.name}</strong><span>${upgrade.desc}</span><small>+ ${upgrade.pro}<br>− ${upgrade.con}</small></button>`; }).join('')}</div></section>`; }
export function errorScreen(message: string): string { return `<section class="next-screen next-error"><p class="next-kicker">FLIGHT DECK ERROR</p><h2>Renderer unavailable</h2><p>${message}</p><button data-next-action="retry" class="next-primary">Retry</button></section>`; }
